name: [yourapp]
directory:
  type: api
  settings:
    jsonrpc_client:
      tls:
        certificate_file: "$DIR/../../certs/[yourapp].crt"
        key_file: "$DIR/../../certs/[yourapp].key"
        ca_certificate_file: "$DIR/../../certs/staging-root.crt"
    ca_certificate_file: "$DIR/../../certs/staging-root.crt"
    endpoints: [ "https://iris.staging.iris-gateway.de:3322/jsonrpc" ]
    server_names: [ "sd-1" ]
channels: # defines all the channels that we want to open when starting the server
  - name: Stdout channel
    type: stdout
    settings: {}
  - name: main gRPC server # accepts incoming gRPC connections to deliver and receive messages
    type: grpc_server
    settings:
      bind_address: "0.0.0.0:4444" # do not change port.
      tls:
        ca_certificate_file: "$DIR/../../certs/staging-root.crt"
        certificate_file: "$DIR/../../certs/[yourapp].crt"
        key_file: "$DIR/../../certs/[yourapp].key"
  - name: main JSON-RPC server # accepts incoming JSONRPC connections to deliver and receive messages
    type: jsonrpc_server
    settings:
      bind_address: "0.0.0.0:5556"
      tls:
        ca_certificate_file: "$DIR/../../certs/staging-root.crt"
        certificate_file: "$DIR/../../certs/[yourapp].crt"
        key_file: "$DIR/../../certs/[yourapp].key"
        verify_client: false
  - name: main JSON-RPC client # creates outgoing JSONRPC connections to deliver and receive messages
    type: jsonrpc_client
    settings:
      endpoint: http://[your-host]:[your-port]/[your-endpoint]
  - name: main gRPC client
    type: grpc_client
    settings:
      tls:
        ca_certificate_file: "$DIR/../../certs/staging-root.crt"
        certificate_file: "$DIR/../../certs/[yourapp].crt"
        key_file: "$DIR/../../certs/[yourapp].key"
